### ISSUE TITLE
Unuseable default

### ISSUE THREAD

**Issue by steven-murray** [RadioAstronomySoftwareGroup/pyuvsim#218]
To me, it doesn't make sense to set a default that can't be used. Here, the file names are enforced to be strings, which means the user *has* to pass them. Much cleaner to leave them as required parameters, then. If you want to enforce that they are passed as keywords, then this can be done in python 3 using ``def func(*, param, param2)`` etc.

https://github.com/RadioAstronomySoftwareGroup/pyuvsim/blob/b10d0af1dea19af672a34f548d2be3e566d74da2/pyuvsim/uvsim.py#L241

Slightly related... I feel like there should be a function which does this initialisation work, but without all the other filename bits -- single responsibility principal and all that.

**Comment by jpober** [comment]
Need a good error message in cases when it's an either/or option with two keywords.

**Comment by aelanman** [comment]
The `init_uvdata_out` function has been replaced with `simsetup.complete_uvdata`, so the referenced line no longer exists.

This was passing along information about the config files used in order to make the file's history string. This is now accomplished by setting the `extra_keywords` in `initialize_uvdata_from_params` and then applying them to the output object at the end of `run_uvsim`.
