### ISSUE TITLE
Update copyright lines

### ISSUE THREAD

**Issue by steven-murray** [RadioAstronomySoftwareGroup/pyuvsim#308]
https://github.com/RadioAstronomySoftwareGroup/pyuvsim/blob/a138f076166648df662684ae59d8d233af24bee0/pyuvsim/simsetup.py#L2

**Comment by bhazelton** [comment]
My understanding is that updating copyrights in existing files is not required. In fact, it's not clear that the statement really needs to be in every file.

I don't really like changing the date because it implies that the file was first written on a later date than it was (which might lead to the false impression that it wasn't copyrighted before the new date). I could see adding a new year in addition to the older year, but only on files that are changed in the new year. But that seems difficult to get right, so my inclination is to just leave the original year in the file.

Some references:
http://www.contentious.com/2007/01/07/copyright-notice-is-the-year-really-necessary/
good discussion here: https://github.com/geodynamics/cig_tools/issues/11

**Comment by aelanman** [comment]
There is the option of ` Copyright Ⓒ 2018 – 2020 `, so you have a full range represented, but I haven't seen that done in source code.

**Comment by bhazelton** [comment]
According to something I read (don't remember exactly where), that's only valid if you made updates in each of the years in the range. Which is definitely true for this repo, so would work for now.

**Comment by aelanman** [comment]
I see the copyright notice as useful for two reasons -- It confirms in each separate document that this is under a BSD license, and that the license is held by RASG. That said, proof of authorship and dates are built into git, so explicitly stating them in each file seems more like a style choice.

**Comment by bhazelton** [comment]
I wasn't suggesting taking them out. I was suggesting not updating the year.
